// apps/test-react/src/App.tsx
/**import { useState } from "react";
import { LmPrototypeButton, LmPrototypeDropdown } from "@lm-prototype/components-react";

import "@lm-prototype/tokens/themes/light.css";
import "@lm-prototype/tokens/themes/dark.css";

declare global {
    namespace JSX {
        interface IntrinsicElements {
            "lm-prototype-icon": React.DetailedHTMLProps<
                React.HTMLAttributes<HTMLElement>,
                HTMLElement
            > & {
                name?: string;
                slot?: string;
            };
        }
    }
}

const Section = ({
                     title,
                     children,
                 }: {
    title: string;
    children: React.ReactNode;
}) => (
    <section style={{ marginBottom: 32 }}>
        <h2
            style={{
                fontSize: 14,
                fontWeight: 600,
                textTransform: "uppercase",
                letterSpacing: "0.05em",
                marginBottom: 12,
                color: "var(--lm-prototype-color-text-secondary)",
            }}
        >
            {title}
        </h2>
        <div
            style={{
                display: "flex",
                gap: 12,
                flexWrap: "wrap",
                alignItems: "center",
            }}
        >
            {children}
        </div>
    </section>
);

export default function App() {
    const [darkMode, setDarkMode] = useState(false);
    const [loading, setLoading] = useState(false);

    const toggleTheme = () => {
        const next = !darkMode;
        setDarkMode(next);
        document.documentElement.dataset["theme"] = next ? "dark" : "";
    };

    const simulateAsync = () => {
        setLoading(true);
        setTimeout(() => setLoading(false), 2000);
    };

    const menuItemStyle: React.CSSProperties = {
        padding: "8px 12px",
        borderRadius: 4,
        cursor: "pointer",
        fontSize: 14,
        textDecoration: "none",
        color: "var(--lm-prototype-color-text-primary)",
    };

    return (
        <div
            style={{
                padding: 40,
                minHeight: "100vh",
                background: "var(--lm-prototype-color-surface-default)",
                color: "var(--lm-prototype-color-text-primary)",
                fontFamily: "var(--lm-prototype-font-family-sans, system-ui)",
            }}
        >
            <header
                style={{
                    display: "flex",
                    justifyContent: "space-between",
                    alignItems: "center",
                    marginBottom: 40,
                    borderBottom: "1px solid var(--lm-prototype-color-border-default)",
                    paddingBottom: 20,
                }}
            >
                <h1 style={{ fontSize: 24, fontWeight: 700, margin: 0 }}>
                    Design System — React Test App
                </h1>
                <LmPrototypeButton variant="tertiary" onClick={toggleTheme}>
                    {darkMode ? "☀️ Light" : "🌙 Dark"}
                </LmPrototypeButton>
            </header>

            <Section title="Variants">
                <LmPrototypeButton variant="primary">Primary</LmPrototypeButton>
                <LmPrototypeButton variant="secondary">Secondary</LmPrototypeButton>
                <LmPrototypeButton variant="tertiary">Tertiary</LmPrototypeButton>
                <LmPrototypeButton variant="danger">Danger</LmPrototypeButton>
            </Section>

            <Section title="Sizes">
                <LmPrototypeButton size="sm">Small</LmPrototypeButton>
                <LmPrototypeButton size="md">Medium</LmPrototypeButton>
                <LmPrototypeButton size="lg">Large</LmPrototypeButton>
            </Section>

            <Section title="With Icons">
                <LmPrototypeButton variant="primary">
                    <lm-prototype-icon slot="start" name="arrow-right" />
                    Continue
                </LmPrototypeButton>
                <LmPrototypeButton variant="secondary">
                    Save
                    <lm-prototype-icon slot="end" name="check" />
                </LmPrototypeButton>
                <LmPrototypeButton variant="danger">
                    <lm-prototype-icon slot="start" name="x" />
                    Remove
                </LmPrototypeButton>
            </Section>

            <Section title="States">
                <LmPrototypeButton loading={loading} onClick={simulateAsync}>
                    {loading ? "Saving…" : "Click to load (2s)"}
                </LmPrototypeButton>
                <LmPrototypeButton disabled>Disabled</LmPrototypeButton>
                <LmPrototypeButton loading>Always loading</LmPrototypeButton>
            </Section>

            <Section title="Form Participation">
                <form
                    onSubmit={(e) => {
                        e.preventDefault();
                        alert("Submitted!");
                    }}
                    style={{ display: "flex", gap: 8, alignItems: "center" }}
                >
                    <input
                        name="q"
                        placeholder="Type something…"
                        style={{
                            padding: "8px 12px",
                            border: "1px solid var(--lm-prototype-color-border-default)",
                            borderRadius: "var(--lm-prototype-radius-md)",
                            background: "var(--lm-prototype-color-surface-raised)",
                            color: "var(--lm-prototype-color-text-primary)",
                            fontSize: "var(--lm-prototype-font-size-md)",
                        }}
                    />
                    <LmPrototypeButton type="submit">Submit</LmPrototypeButton>
                    <LmPrototypeButton type="reset" variant="tertiary">
                        Reset
                    </LmPrototypeButton>
                </form>
            </Section>

            <Section title="Dropdown">
                <div style={{ minHeight: 250 }}>
                    <LmPrototypeDropdown
                        variant="secondary"
                        size="md"
                        onLmChange={(e: any) => console.log("Dropdown open state:", e.detail.open)}
                    >
                        <span slot="label">Options</span>

                        <div style={{ padding: 8, display: "flex", flexDirection: "column", gap: 4, minWidth: 180 }}>
                            <a href="#" style={menuItemStyle}>
                                Account settings
                            </a>
                            <a href="#" style={menuItemStyle}>
                                Support
                            </a>
                            <hr style={{ border: 0, borderTop: "1px solid var(--lm-prototype-color-border-default)", margin: "4px 0" }} />
                            <a href="#" style={{ ...menuItemStyle, color: "var(--lm-prototype-color-danger-default)" }}>
                                Sign out
                            </a>
                        </div>
                    </LmPrototypeDropdown>
                </div>
            </Section>
        </div>
    );
}*/
import { useState } from "react";
import {
    LmPrototypeButton,
    LmPrototypeDropdown,
    LmPrototypeDropdownItem,
    LmPrototypeInput,
    LmPrototypeCheckbox
} from "@lm-prototype/components-react";

import "@lm-prototype/tokens/themes/light.css";
import "@lm-prototype/tokens/themes/dark.css";

const Section = ({ title, children }: { title: string; children: React.ReactNode }) => (
    <section style={{ marginBottom: 32, maxWidth: 500 }}>
        <h2 style={{ fontSize: 14, fontWeight: 600, textTransform: "uppercase", letterSpacing: "0.05em", marginBottom: 12, color: "var(--lm-prototype-color-text-secondary)" }}>
            {title}
        </h2>
        <div>{children}</div>
    </section>
);

export default function App() {
    const [darkMode, setDarkMode] = useState(false);
    const [showAdvanced, setShowAdvanced] = useState(false);

    const toggleTheme = () => {
        const next = !darkMode;
        setDarkMode(next);
        document.documentElement.dataset["theme"] = next ? "dark" : "";
    };

    const handleSubmit = (e: React.FormEvent<HTMLFormElement>) => {
        e.preventDefault();
        const data = new FormData(e.currentTarget);
        alert('Sparad data från Web Components: \n\n' + JSON.stringify(Object.fromEntries(data as any), null, 2));
    };

    return (
        <div style={{ padding: 40, minHeight: "100vh", background: "var(--lm-prototype-color-surface-default)", color: "var(--lm-prototype-color-text-primary)", fontFamily: "var(--lm-prototype-font-family-sans, system-ui)" }}>
            <header style={{ display: "flex", justifyContent: "space-between", alignItems: "center", marginBottom: 40, borderBottom: "1px solid var(--lm-prototype-color-border-default)", paddingBottom: 20, maxWidth: 800 }}>
                <h1 style={{ fontSize: 24, fontWeight: 700, margin: 0 }}>Design System — React Test App</h1>
                <LmPrototypeButton variant="tertiary" icon="chevron-down" onClick={toggleTheme}>
                    {darkMode ? "Light Mode" : "Dark Mode"}
                </LmPrototypeButton>
            </header>

            <Section title="Testscenario: Konfigurera Strategi">
                <form
                    onSubmit={handleSubmit}
                    style={{ display: "flex", flexDirection: "column", gap: 20, padding: 24, border: "1px solid var(--lm-prototype-color-border-default)", borderRadius: 8, background: "var(--lm-prototype-color-surface-raised)" }}
                >
                    <LmPrototypeInput
                        name="configName"
                        label="Konfigurationsnamn"
                        placeholder="T.ex. Nattkörning"
                        required
                    />

                    <LmPrototypeDropdown
                        name="strategy"
                        label="Aktiv strategi"
                        placeholder="Välj en strategi..."
                    >
                        <LmPrototypeDropdownItem value="print" icon="x">
                            PrintStrategy
                        </LmPrototypeDropdownItem>

                        <LmPrototypeDropdownItem value="export" icon="loader">
                            ExportStrategy
                        </LmPrototypeDropdownItem>

                        <LmPrototypeDropdownItem value="import" icon="x">
                            ImportStrategy
                        </LmPrototypeDropdownItem>
                    </LmPrototypeDropdown>

                    <LmPrototypeCheckbox
                        name="advanced"
                        value="enabled"
                        label="Aktivera avancerade inställningar"
                        onChange={(e: any) => setShowAdvanced(e.target.checked)}
                    />

                    {showAdvanced && (
                        <div style={{ padding: 16, background: "var(--lm-prototype-color-surface-subtle)", borderRadius: 6, borderLeft: "3px solid var(--lm-prototype-color-action-primary)" }}>
                            <LmPrototypeInput
                                name="apiKey"
                                label="API-nyckel"
                                placeholder="Skriv in din nyckel..."
                                icon="check"
                            />
                        </div>
                    )}

                    <div style={{ display: "flex", gap: 12, marginTop: 8, paddingTop: 16, borderTop: "1px solid var(--lm-prototype-color-border-default)" }}>
                        <LmPrototypeButton type="submit" icon="check">Spara konfiguration</LmPrototypeButton>
                        <LmPrototypeButton type="reset" variant="tertiary">Återställ</LmPrototypeButton>
                    </div>
                </form>
            </Section>
        </div>
    );
}

// apps/test-angular/src/app/app.component.ts
/**import { Component, CUSTOM_ELEMENTS_SCHEMA } from '@angular/core';
import { CommonModule } from '@angular/common';

import '@lm-prototype/components/lm-prototype-button';
import '@lm-prototype/components/lm-prototype-dropdown';

interface ButtonDemo {
  variant: 'primary' | 'secondary' | 'tertiary' | 'danger';
  label: string;
}

//@Component({
  selector: 'app-root',
  standalone: true,
  imports: [CommonModule],
  schemas: [CUSTOM_ELEMENTS_SCHEMA],
  template: `
    <div class="app">
      <header class="app-header">
        <h1>Design System — Angular Test App</h1>
        <lm-prototype-button variant="tertiary" (click)="toggleTheme()">
          {{ darkMode ? '☀️ Light' : '🌙 Dark' }}
        </lm-prototype-button>
      </header>

      <main class="app-main">
        <section class="demo-section">
          <h2 class="demo-title">Variants</h2>
          <div class="demo-row">
            <lm-prototype-button variant="primary">Primary</lm-prototype-button>
            <lm-prototype-button variant="secondary">Secondary</lm-prototype-button>
            <lm-prototype-button variant="tertiary">Tertiary</lm-prototype-button>
            <lm-prototype-button variant="danger">Danger</lm-prototype-button>
            <lm-prototype-button variant=""
          </div>
        </section>

        <section class="demo-section">
          <h2 class="demo-title">Sizes</h2>
          <div class="demo-row">
            <lm-prototype-button size="sm">Small</lm-prototype-button>
            <lm-prototype-button size="md">Medium</lm-prototype-button>
            <lm-prototype-button size="lg">Large</lm-prototype-button>
          </div>
        </section>

        <section class="demo-section">
          <h2 class="demo-title">With Icons</h2>
          <div class="demo-row">
            <lm-prototype-button variant="primary">
              <lm-prototype-icon slot="start" name="arrow-right"></lm-prototype-icon>
              Continue
            </lm-prototype-button>
            <lm-prototype-button variant="secondary">
              Save
              <lm-prototype-icon slot="end" name="check"></lm-prototype-icon>
            </lm-prototype-button>
            <lm-prototype-button variant="danger">
              <lm-prototype-icon slot="start" name="x"></lm-prototype-icon>
              Remove
            </lm-prototype-button>
          </div>
        </section>

        <section class="demo-section">
          <h2 class="demo-title">States</h2>
          <div class="demo-row">
            <lm-prototype-button [attr.loading]="loading || null" (click)="simulateAsync()">
              {{ loading ? 'Saving…' : 'Click to load (2s)' }}
            </lm-prototype-button>
            <lm-prototype-button disabled>Disabled</lm-prototype-button>
            <lm-prototype-button loading>Always loading</lm-prototype-button>
          </div>
        </section>

        <section class="demo-section">
          <h2 class="demo-title">Form Participation</h2>
          <form (submit)="onSubmit($event)" class="demo-form">
            <input
              name="q"
              placeholder="Type something…"
              class="demo-input"
            />
            <lm-prototype-button type="submit">Submit</lm-prototype-button>
            <lm-prototype-button type="reset" variant="tertiary">Reset</lm-prototype-button>
          </form>
        </section>

        <section class="demo-section">
          <h2 class="demo-title">Dropdown</h2>
          <div style="min-height: 250px;">
            <lm-prototype-dropdown variant="primary" size="lg">
              <span slot="label">Options</span>

              <div style="padding: 8px; display: flex; flex-direction: column; gap: 4px; min-width: 180px;">
                <a href="#"
                   style="padding: 8px 12px; border-radius: 4px; cursor: pointer; font-size: 14px; font-family: system-ui, sans-serif; color: #374151; text-decoration: none;">Account
                  settings</a>
                <a href="#"
                   style="padding: 8px 12px; border-radius: 4px; cursor: pointer; font-size: 14px; font-family: system-ui, sans-serif; color: #374151; text-decoration: none;">Support</a>
                <hr style="border: 0; border-top: 1px solid #e5e7eb; margin: 4px 0;">
                <a href="#"
                   style="padding: 8px 12px; border-radius: 4px; cursor: pointer; font-size: 14px; font-family: system-ui, sans-serif; color: #374151; text-decoration: none; color: #dc2626;">Sign
                  out</a>
              </div>

            </lm-prototype-dropdown>
          </div>
        </section>
      </main>
    </div>
  `,
  styles: [`
    .app {
      padding: 40px;
      min-height: 100vh;
    }

    .app-header {
      display: flex;
      justify-content: space-between;
      align-items: center;
      margin-bottom: 40px;
      padding-bottom: 20px;
      border-bottom: 1px solid var(--lm-prototype-color-border-default);
    }

    h1 {
      font-size: 24px;
      font-weight: 700;
      margin: 0;
    }

    .demo-section {
      margin-bottom: 32px;
    }

    .demo-title {
      font-size: 12px;
      font-weight: 600;
      text-transform: uppercase;
      letter-spacing: 0.05em;
      color: var(--lm-prototype-color-text-secondary);
      margin: 0 0 12px;
    }

    .demo-row {
      display: flex;
      gap: 12px;
      flex-wrap: wrap;
      align-items: center;
    }

    .demo-form {
      display: flex;
      gap: 8px;
      align-items: center;
    }

    .demo-input {
      padding: 8px 12px;
      border: 1px solid var(--lm-prototype-color-border-default);
      border-radius: var(--lm-prototype-radius-md);
      background: var(--lm-prototype-color-surface-raised);
      color: var(--lm-prototype-color-text-primary);
      font-size: var(--lm-prototype-font-size-md);
      font-family: inherit;
    }

    .demo-input:focus {
      outline: 2px solid var(--lm-prototype-color-border-focus);
      outline-offset: 2px;
    }
  `],
})
export class AppComponent {
  darkMode = false;
  loading = false;

  toggleTheme(): void {
    this.darkMode = !this.darkMode;
    document.documentElement.dataset['theme'] = this.darkMode ? 'dark' : '';
  }

  simulateAsync(): void {
    this.loading = true;
    setTimeout(() => { this.loading = false; }, 2000);
  }

  onSubmit(event: Event): void {
    event.preventDefault();
    const data = new FormData(event.target as HTMLFormElement);
    alert('Submitted: ' + JSON.stringify(Object.fromEntries(data as any)));
  }
}*/
import { Component, CUSTOM_ELEMENTS_SCHEMA } from '@angular/core';
import { CommonModule } from '@angular/common';

import '@lm-prototype/components/lm-prototype-button';
import '@lm-prototype/components/lm-prototype-input';
import '@lm-prototype/components/lm-prototype-dropdown';
import '@lm-prototype/components/lm-prototype-dropdown-item';
import '@lm-prototype/components/lm-prototype-checkbox';
import '@lm-prototype/icons/lm-prototype-icon';

@Component({
  selector: 'app-root',
  standalone: true,
  imports: [CommonModule],
  schemas: [CUSTOM_ELEMENTS_SCHEMA],
  template: `
    <div class="app">
      <header class="app-header">
        <h1>Design System — Angular Test App</h1>
        <lm-prototype-button variant="tertiary" icon="check" (click)="toggleTheme()">
          {{ darkMode ? 'Light Mode' : 'Dark Mode' }}
        </lm-prototype-button>
      </header>

      <main class="app-main">
        <section class="demo-section">
          <h2 class="demo-title">Testscenario: Konfigurera Strategi</h2>

          <form (submit)="onSubmit($event)" class="demo-form-card">

            <lm-prototype-input
              name="configName"
              label="Konfigurationsnamn"
              placeholder="T.ex. Nattkörning"
              required>
            </lm-prototype-input>

            <lm-prototype-dropdown
              name="strategy"
              label="Aktiv strategi"
              placeholder="Välj en strategi...">

              <lm-prototype-dropdown-item value="print" icon="check">
                PrintStrategy
              </lm-prototype-dropdown-item>

              <lm-prototype-dropdown-item value="export" icon="loader">
                ExportStrategy
              </lm-prototype-dropdown-item>

              <lm-prototype-dropdown-item value="import" icon="check">
                ImportStrategy
              </lm-prototype-dropdown-item>
            </lm-prototype-dropdown>

            <lm-prototype-checkbox
              name="advanced"
              value="enabled"
              label="Aktivera avancerade inställningar"
              (change)="onAdvancedToggle($event)">
            </lm-prototype-checkbox>

            <div *ngIf="showAdvanced" class="advanced-panel">
              <lm-prototype-input
                name="apiKey"
                label="API-nyckel"
                placeholder="Skriv in din nyckel..."
                icon="arrow-right">
              </lm-prototype-input>
            </div>

            <div class="form-actions">
              <lm-prototype-button type="submit" icon="check">Spara konfiguration</lm-prototype-button>
              <lm-prototype-button type="reset" variant="tertiary">Återställ</lm-prototype-button>
            </div>

          </form>
        </section>
      </main>
    </div>
  `,
  styles: [`
    .app { padding: 40px; min-height: 100vh; font-family: system-ui, sans-serif; }
    .app-header { display: flex; justify-content: space-between; align-items: center; margin-bottom: 40px; padding-bottom: 20px; border-bottom: 1px solid #e5e7eb; }
    h1 { font-size: 24px; font-weight: 700; margin: 0; }
    .demo-section { margin-bottom: 32px; max-width: 500px; }
    .demo-title { font-size: 12px; font-weight: 600; text-transform: uppercase; letter-spacing: 0.05em; color: #6b7280; margin: 0 0 12px; }

    .demo-form-card {
      display: flex;
      flex-direction: column;
      gap: 20px;
      padding: 24px;
      border: 1px solid #e5e7eb;
      border-radius: 8px;
      background: #ffffff;
    }

    .advanced-panel {
      padding: 16px;
      background: #f9fafb;
      border-radius: 6px;
      border-left: 3px solid #005A9C;
    }

    .form-actions {
      display: flex;
      gap: 12px;
      margin-top: 8px;
      padding-top: 16px;
      border-top: 1px solid #e5e7eb;
    }
  `],
})
export class AppComponent {
  darkMode = false;
  showAdvanced = false;

  toggleTheme(): void {
    this.darkMode = !this.darkMode;
    document.documentElement.dataset['theme'] = this.darkMode ? 'dark' : '';
  }

  onAdvancedToggle(event: Event): void {
    const target = event.target as HTMLInputElement;
    this.showAdvanced = target.checked;
  }

  onSubmit(event: Event): void {
    event.preventDefault();
    const form = event.target as HTMLFormElement;
    const data = new FormData(form);

    alert('Sparad data från Web Components: \n\n' + JSON.stringify(Object.fromEntries(data as any), null, 2));
  }
}
